const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const {pipeline}=require('node:stream/promises');
const MAGIC='CRUCIBLE-SOURCE-BUNDLE-V1',TAG_BYTES=16,PROJECT='github:jonathanblunt1214-lgtm/The-Crucible',REPOSITORY='jonathanblunt1214-lgtm/The-Crucible',REF='refs/heads/development';
const shaFile=(file)=>{const h=crypto.createHash('sha256'),fd=fs.openSync(file,'r'),b=Buffer.allocUnsafe(1024*1024);try{let n;while((n=fs.readSync(fd,b,0,b.length,null))>0)h.update(b.subarray(0,n));}finally{fs.closeSync(fd);}return h.digest('hex');};
const key=()=>{const value=Buffer.from(process.env.CRUCIBLE_VETTED_BUNDLE_KEY||'','base64');if(value.length!==32)throw new Error('Vetted source decryption key is unavailable.');return value;};
function join(root,output){const manifest=JSON.parse(fs.readFileSync(path.join(root,'encrypted-chunks.json'),'utf8')),fd=fs.openSync(output,'wx',0o600);try{for(const item of manifest.chunks){const file=path.join(root,item.name);if(fs.statSync(file).size!==item.bytes||shaFile(file)!==item.sha256)throw new Error(`Vetted ciphertext chunk mismatch: ${item.name}`);fs.writeSync(fd,fs.readFileSync(file));}}finally{fs.closeSync(fd);}if(shaFile(output)!==manifest.encryptedSha256)throw new Error('Vetted ciphertext manifest mismatch.');return manifest;}
function verifyApproval(root,publicKey,manifest){const reportFile=path.join(root,'encrypted-custody-report.json'),signatureFile=path.join(root,'encrypted-custody-report.sig'),bytes=fs.readFileSync(reportFile),report=JSON.parse(bytes);if(!crypto.verify(null,bytes,publicKey,fs.readFileSync(signatureFile)))throw new Error('Independent oversight custody signature is invalid.');if(report.schemaVersion!==1||report.projectId!==PROJECT||report.decision!=='PASS_TO_LEARNING_WORKER'||report.independentOversight!==true||report.scientificProofSatisfied!==false||report.promotionAuthorized!==false||report.vettedCiphertextSha256!==manifest.encryptedSha256||!Array.isArray(report.sourceReviews))throw new Error('Independent oversight did not approve this exact ciphertext.');const reportHash=crypto.createHash('sha256').update(bytes).digest('hex'),approvals=[];for(const item of report.sourceReviews){if(item.automaticallyTrusted!==false||!/^[a-f0-9]{64}$/.test(item.contentSha256||'')||!['approved-for-bounded-extraction','quarantined'].includes(item.decision))throw new Error('Oversight source review is invalid.');if(item.decision==='approved-for-bounded-extraction')approvals.push({contentSha256:item.contentSha256,decision:'approved-for-extraction',oversightReportSha256:reportHash,candidateId:item.sourceId,decidedAt:report.generatedAt});}if(approvals.length<1)throw new Error('Independent oversight approved no sources for extraction.');return{schemaVersion:1,projectId:PROJECT,approvals,quarantined:report.sourceReviews.length-approvals.length,updatedAt:report.generatedAt};}
async function decrypt(input,output){const fd=fs.openSync(input,'r'),probe=Buffer.alloc(8192),count=fs.readSync(fd,probe,0,probe.length,0);fs.closeSync(fd);const newline=probe.subarray(0,count).indexOf(10),encoded=probe.subarray(0,newline+1),header=JSON.parse(encoded.toString('utf8'));if(header.magic!==MAGIC||header.stage!=='oversight-vetted'||header.projectId!==PROJECT||header.repository!==REPOSITORY||header.ref!==REF)throw new Error('Vetted encrypted custody identity mismatch.');const size=fs.statSync(input).size,tag=Buffer.alloc(TAG_BYTES),tagFd=fs.openSync(input,'r');fs.readSync(tagFd,tag,0,TAG_BYTES,size-TAG_BYTES);fs.closeSync(tagFd);const decipher=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(header.iv,'base64'));decipher.setAAD(encoded);decipher.setAuthTag(tag);await pipeline(fs.createReadStream(input,{start:encoded.length,end:size-TAG_BYTES-1}),decipher,fs.createWriteStream(output,{flags:'wx',mode:0o600}));if(shaFile(output)!==header.plaintextSha256)throw new Error('Vetted plaintext authentication failed.');return header;}
async function main(){const [root,output,publicKeyFile,approvalFile]=process.argv.slice(2);if(!root||!output||!publicKeyFile||!approvalFile)throw new Error('Usage: vetted-custody.js <vetted-root> <output-tar> <public-key> <approval-file>');const ciphertext=`${output}.enc`,manifest=join(root,ciphertext),approvals=verifyApproval(root,fs.readFileSync(publicKeyFile),manifest);fs.writeFileSync(approvalFile,`${JSON.stringify(approvals,null,2)}\n`,{flag:'wx',mode:0o600});await decrypt(ciphertext,output);fs.rmSync(ciphertext,{force:true});}
if(require.main===module)main().catch((error)=>{console.error(error.message);process.exitCode=1;});module.exports={join,verifyApproval,decrypt};
